version: "2"

services:
  app:
    build : .
    links:
      - mongo
      - redis
    depends_on:  
      - mongo
      - redis
    command: npm run test  

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6378:6379"    